-- Jhonatan Andrade Quiterio, Gabriela Rocca, Thaiza dos Santos 

-- Criação do banco de dados e uso
CREATE DATABASE BD_ED;
GO
USE BD_ED;
GO

-- Criação do esquema
CREATE SCHEMA WALLET_BD;
GO

-- Tabelas
CREATE TABLE WALLET_BD.MOEDA (
	CODIGO_MOEDA VARCHAR(3),
	NOME VARCHAR(100),
	PRIMARY KEY (CODIGO_MOEDA)
);

CREATE TABLE WALLET_BD.CORRETORA (
	CODIGO_CORRETORA INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100)
);

CREATE TABLE WALLET_BD.CLIENTE (
	CODIGO_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	CELULAR VARCHAR(100),
	PASS_HASH VARCHAR(100),
	MOEDA_PRINCIPAL VARCHAR(3)
        FOREIGN KEY REFERENCES WALLET_BD.MOEDA(CODIGO_MOEDA),
);

CREATE TABLE WALLET_BD.PARES_MOEDAS (
	CODIGO_MOEDA_BASE VARCHAR(3)
        FOREIGN KEY  REFERENCES WALLET_BD.MOEDA(CODIGO_MOEDA),
	CODIGO_MOEDA_COTACAO VARCHAR(3)
        FOREIGN KEY  REFERENCES WALLET_BD.MOEDA(CODIGO_MOEDA),
	VALOR DECIMAL(18,2),
	PRIMARY KEY (CODIGO_MOEDA_BASE, CODIGO_MOEDA_COTACAO)
);

CREATE TABLE WALLET_BD.CARTEIRA (
	
	CODIGO_CLIENTE INT
        FOREIGN KEY REFERENCES WALLET_BD.CLIENTE(CODIGO_CLIENTE),
	CODIGO_CORRETORA INT
        FOREIGN KEY REFERENCES WALLET_BD.CORRETORA(CODIGO_CORRETORA),
	ENDERECO VARCHAR(100),
	PRIMARY KEY (ENDERECO)

);

CREATE TABLE WALLET_BD.ITEM_CARTEIRA (
	ENDERECO VARCHAR(100)
        FOREIGN KEY REFERENCES WALLET_BD.CARTEIRA(ENDERECO),
	CODIGO_MOEDA VARCHAR(3)
        FOREIGN KEY REFERENCES WALLET_BD.MOEDA(CODIGO_MOEDA),
    QUANTIDADE DECIMAL(18,2),
	PRIMARY KEY (ENDERECO)
);

-- Índices para colunas mais consultadas
CREATE INDEX IDX_NOME_MOEDA ON WALLET_BD.MOEDA (NOME);
CREATE INDEX IDX_NOME_CLIENTE ON WALLET_BD.CLIENTE (NOME);
CREATE INDEX IDX_NOME_CORRETORA ON WALLET_BD.CORRETORA (NOME);

-- Inserção de dados
INSERT INTO WALLET_BD.MOEDA VALUES
('ETH','Ethereum'),
('LTS','Litecoin'),
('BTC','Bitcoin'),
('USD','Dólar'),
('BRL','Real');

INSERT INTO WALLET_BD.CLIENTE VALUES
('Ze','lerolero@hotmail.com', '4166666666', 'dkjgndhzih', 'BTC'),
('Blebos','blirolero@hotmail.com', '41) 6566-6666', 'skjdfhowlk', 'BRL'),
('Blipo','clerolero@hotmail.com', '(41) 6667-6666', 'akjsfnkajdfij', 'ETH'),
('Et de varginha','varginholero@hotmail.com', '(87) 6666-66456', 'alkscieo', 'LTS'),
('biribo','popilero@hotmail.com', '(41) 6666-6321', 'ajsnfuie', 'USD');

INSERT INTO WALLET_BD.CORRETORA VALUES
('Primo rico'),
('Binance'),
('Mercado Bitcoin'),
('NovaDAX'),
('ota');

INSERT INTO WALLET_BD.PARES_MOEDAS VALUES
('BTC','USD',60356.70),
('ETH','USD',2570.52),
('LTS','USD',63.59),
('USD','USD',5.10),
('BRL','USD',1.00),
('BRL','BRL',1.00);


-- Inserção de carteiras (endereços fictícios)
INSERT INTO WALLET_BD.CARTEIRA VALUES
(1, 1, '0x1234567890abcdef1234567890abcdef12345678'),
(1, 2, '0xabcdef1234567890abcdef1234567890abcdef12'),
(2, 3, '0x7890abcdef1234567890abcdef1234567890abcd'),
(3, 4, '0x4567890abcdef1234567890abcdef1234567890ab'),
(4, 5, '0x234567890abcdef1234567890abcdef1234567890');

INSERT INTO WALLET_BD.ITEM_CARTEIRA VALUES
('0x1234567890abcdef1234567890abcdef12345678','BTC',1.5),
('0xabcdef1234567890abcdef1234567890abcdef12','ETH',10.0),
('0x7890abcdef1234567890abcdef1234567890abcd','USD',20.0),
('0x4567890abcdef1234567890abcdef1234567890ab','USD',100.0),
('0x234567890abcdef1234567890abcdef1234567890','BRL',500.0);

-- Consultas
SELECT * FROM WALLET_BD.MOEDA;
SELECT * FROM WALLET_BD.CLIENTE;
SELECT * FROM WALLET_BD.CORRETORA;
SELECT * FROM WALLET_BD.PARES_MOEDAS;
SELECT * FROM WALLET_BD.CARTEIRA;
SELECT * FROM WALLET_BD.ITEM_CARTEIRA;

-- Listar saldo atual por usuário cadastrado, mostrando a descrição da moeda e o valor da carteira.
SELECT 
    C.NOME AS Cliente,
    M.NOME AS Moeda,
    IC.QUANTIDADE AS Saldo,
    CA.ENDERECO AS Endereco_Carteira
FROM  WALLET_BD.CLIENTE C
JOIN  WALLET_BD.CARTEIRA CA ON C.CODIGO_CLIENTE = CA.CODIGO_CLIENTE
JOIN  WALLET_BD.ITEM_CARTEIRA IC ON CA.ENDERECO = IC.ENDERECO
JOIN  WALLET_BD.MOEDA M ON IC.CODIGO_MOEDA = M.CODIGO_MOEDA;


-- Criar objetos que facilitem a consulta dos dados como VISÕES,FUNÇÕES entre outro

-- VISÕES

CREATE VIEW WALLET_BD.VW_SALDO_DETALHADO AS
SELECT 
    CLI.NOME AS CLIENTE,
    COR.NOME AS CORRETORA,
    MOE.NOME AS MOEDA,
    ITE.QUANTIDADE,
    ITE.ENDERECO
FROM WALLET_BD.CLIENTE CLI
JOIN WALLET_BD.CARTEIRA CAR ON CLI.CODIGO_CLIENTE = CAR.CODIGO_CLIENTE
JOIN WALLET_BD.CORRETORA COR ON CAR.CODIGO_CORRETORA = COR.CODIGO_CORRETORA
JOIN WALLET_BD.ITEM_CARTEIRA ITE ON CAR.ENDERECO = ITE.ENDERECO
JOIN WALLET_BD.MOEDA MOE ON ITE.CODIGO_MOEDA = MOE.CODIGO_MOEDA;

SELECT * FROM WALLET_BD.VW_SALDO_DETALHADO

GO

-- FUNÇÕES

CREATE FUNCTION WALLET_BD.FN_CONVERTER_SALDO (
    @QUANTIDADE DECIMAL(18,2),
    @MOEDA_BASE VARCHAR(3),
    @MOEDA_COTACAO VARCHAR(3)
)
RETURNS DECIMAL(18,2)
AS
BEGIN
    DECLARE @VALOR_CONVERTIDO DECIMAL(18,2);
    DECLARE @TAXA DECIMAL(18,2);

    SELECT @TAXA = VALOR 
    FROM WALLET_BD.PARES_MOEDAS 
    WHERE CODIGO_MOEDA_BASE = @MOEDA_BASE 
      AND CODIGO_MOEDA_COTACAO = @MOEDA_COTACAO;

    SET @VALOR_CONVERTIDO = @QUANTIDADE * ISNULL(@TAXA, 0);

    RETURN @VALOR_CONVERTIDO;
END;
GO

SELECT 
    C.NOME AS Cliente,
    M.NOME AS Moeda_Original,
    IC.QUANTIDADE AS Saldo_Original,
    'USD' AS Moeda_Destino,
    WALLET_BD.FN_CONVERTER_SALDO(IC.QUANTIDADE, M.CODIGO_MOEDA, 'USD') AS Saldo_Convertido_USD
FROM WALLET_BD.CLIENTE C
JOIN WALLET_BD.CARTEIRA CA ON C.CODIGO_CLIENTE = CA.CODIGO_CLIENTE
JOIN WALLET_BD.ITEM_CARTEIRA IC ON CA.ENDERECO = IC.ENDERECO
JOIN WALLET_BD.MOEDA M ON IC.CODIGO_MOEDA = M.CODIGO_MOEDA;



-- =========================================
-- ROLLBACK COMPLETO DO BANCO BD_ED
-- =========================================

DROP VIEW WALLET_BD.VW_SALDO_DETALHADO;

DROP FUNCTION WALLET_BD.FN_CONVERTER_SALDO;

DROP INDEX IDX_NOME_MOEDA ON WALLET_BD.MOEDA;

DROP INDEX IDX_NOME_CLIENTE ON WALLET_BD.CLIENTE;

DROP INDEX IDX_NOME_CORRETORA ON WALLET_BD.CORRETORA;

DROP TABLE WALLET_BD.ITEM_CARTEIRA;

DROP TABLE WALLET_BD.CARTEIRA;

DROP TABLE WALLET_BD.PARES_MOEDAS;

DROP TABLE WALLET_BD.CLIENTE;

DROP TABLE WALLET_BD.CORRETORA;

DROP TABLE WALLET_BD.MOEDA;


USE master;
DROP DATABASE BD_ED;
