CREATE DATABASE BD_ED;
USE BD_ED;
GO
DROP DATABASE BD_ED;
GO
CREATE SCHEMA WALLET_BD;
GO

CREATE TABLE WALLET_BD.MOEDA(
	CODIGO_MOEDA VARCHAR(3),
	NOME VARCHAR(20),
	PRIMARY KEY (CODIGO_MOEDA)
);
CREATE TABLE WALLET_BD.PARES_MOEDAS(
	CODIGO_MOEDA_BASE VARCHAR(3),
	CODIGO_MOEDA_COTACAO VARCHAR(3),
	VALOR REAL,
);
CREATE TABLE WALLET_BD.ITEM_CARTEIRA(
	CODIGO_ITEM_CARTEIRA INT,
	ENDERECO VARCHAR(100),
	QUANTIDADE REAL,
	CODIGO_MOEDA VARCHAR(3)
		FOREIGN KEY REFERENCES WALLET_BD.MOEDA(CODIGO_MOEDA),
	PRIMARY KEY (CODIGO_ITEM_CARTEIRA)
);
CREATE TABLE WALLET_BD.CORRETORA(
	CODIGO_CORRETORA INT,
	NOME VARCHAR(30),
	PRIMARY KEY (CODIGO_CORRETORA)
);
CREATE TABLE WALLET_BD.CLIENTE(
	CODIGO_CLIENTE INT,
	NOME VARCHAR(30),
	EMAIL VARCHAR(30),
	CELULAR VARCHAR(20),
	PASS_HASH VARCHAR(100),
	MOEDA_PRINCIPAL VARCHAR(3),
	PRIMARY KEY (CODIGO_CLIENTE)
);
CREATE TABLE WALLET_BD.CARTEIRA(
	CODIGO_CLIENTE INT
		FOREIGN KEY REFERENCES WALLET_BD.CLIENTE(CODIGO_CLIENTE),
	CODIGO_CORRETORA INT
		FOREIGN KEY REFERENCES WALLET_BD.CORRETORA(CODIGO_CORRETORA),
	ENDERECO VARCHAR(100),
);
GO
INSERT INTO  WALLET_BD.MOEDA VALUES
('ETH','Ethereum'),
('LTS','Litecoin'),
('BTC','Bitcoin'),
('USD','Dólar'),
('BRL','Real')
SELECT * FROM  WALLET_BD.MOEDA;
GO

INSERT INTO  WALLET_BD.CLIENTE VALUES
('Ze','lerolero@hotmail.com', '4166666666', 'dkjgndhzih', 'BTC'),
('Blebos','blirolero@hotmail.com', '41) 6566-6666', 'skjdfhowlk', 'BRL'),
('Blipo','clerolero@hotmail.com', '(41) 6667-6666', 'akjsfnkajdfij', 'ETH'),
('Et de varginha','varginholero@hotmail.com', '(87) 6666-66456', 'alkscieo', 'LTS'),
('biribo','popilero@hotmail.com', '(41) 6666-6321', 'ajsnfuie', 'USD')
SELECT * FROM  WALLET_BD.CLIENTE;

